security:
    # Password hashing configuration
    password_hashers:
        App\Entity\User:
            # algorithm: bcrypt
             algorithm: plaintext

    # User providers
    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: username

    # Firewalls configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            
            lazy: true
            provider: users_in_database
            entry_point: form_login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true  # Enable CSRF protection
                csrf_token_id: authenticate  # Set the CSRF token ID
            logout:
                path: app_logout
                target: app_login
            custom_authenticator: App\Security\LoginFormAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    # Access control rules
    access_control:
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/game, roles: ROLE_USER }

# Test environment configuration
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4  # Lowest possible value for bcrypt
                time_cost: 3  # Lowest possible value for argon
                memory_cost: 10  # Lowest possible value for argon