index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    defaults:
        _locale: 'en'
    requirements:
        _locale: 'en|fa' # The locales you want to support

controllers:
    resource: '../src/Controller/'
    namespace: App\Controller
    type: attribute
